### PR TITLE
added roleinfo command

### LINKED ISSUE #24: ;roleinfo
Gives information such as
- color
- if you have the following permissions (dyno lists useless ones)
  - Audit Log
  - Manage Roles/Server/Channels
  - Kick/Ban
  - Manage messages
  - Mention @ everyone and the such
Status
- high council vs lower council vs citizen

### PR DESCRIPTION
**Pull request by sourTaste000**
closes #24

### CODE REVIEW

**Comment by sourTaste000** [comment]
wtf so many commits

**Comment by sourTaste000** [comment]
wait

**Comment by l1ving** [comment]
Your git history is messed up. I'll fix it tomorrow morning if you want

**Comment by sourTaste000** [comment]
fixed, check #55

**Pull request closed without merging**
