### PR TITLE
[refactor] ReflectionUtils

### PR DESCRIPTION
**Pull request by Xiaro**
Use the new reflection utils to register the commands

### CODE REVIEW

**Review by l1ving — COMMENTED** [review]
Lgtm

**Review by l1ving — APPROVED** [review]
Looks good to me

**Comment by sourTaste000** [comment]
why is this draft

**Comment by l1ving** [comment]
it only works in dev env ll

**Review by sourTaste000 — CHANGES_REQUESTED** [review]
update the submodules please

**Comment by l1ving** [comment]
Closing this until commons has the fixed reflection utils (if we ever want to do this)

**Pull request closed without merging**
